import type { MarkdownRenderer } from 'vitepress';

/** Localize labels generated by Markdown rendering only for Chinese pages. */
export function localizeChineseMarkdown(md: MarkdownRenderer) {
	const fence = md.renderer.rules.fence!;
	md.renderer.rules.fence = (...args) => {
		const html = fence(...args);
		return args[3].relativePath?.startsWith('zh/')
			? html.replace('title="Copy Code"', 'title="复制代码"')
			: html;
	};

	const linkOpen = md.renderer.rules.link_open;
	md.renderer.rules.link_open = (tokens, index, options, env, self) => {
		const token = tokens[index];
		const label = token.attrGet('aria-label');
		if (env.relativePath?.startsWith('zh/') && label?.startsWith('Permalink to "')) {
			const title = label.slice('Permalink to "'.length, -1).replace(/\s*\{#[^}]+\}$/, '');
			token.attrSet('aria-label', `跳转到“${title}”`);
		}
		return linkOpen
			? linkOpen(tokens, index, options, env, self)
			: self.renderToken(tokens, index, options);
	};
}
