// Compatibility exports: all document operations are owned by OOXML core.
import { apiToolsElementTools as operations } from 'ooxml-core/pptx/automation';
export type AddElementParams = operations.AddElementParams;
export type AddElementResult = operations.AddElementResult;
export const addElement = operations.addElement;
export type UpdateElementParams = operations.UpdateElementParams;
export const updateElement = operations.updateElement;
export type RenameElementParams = operations.RenameElementParams;
export const renameElement = operations.renameElement;
export type DeleteElementsParams = operations.DeleteElementsParams;
export const deleteElements = operations.deleteElements;
export type ArrangeElementsParams = operations.ArrangeElementsParams;
export const arrangeElements = operations.arrangeElements;
export type CloneElementParams = operations.CloneElementParams;
export type CloneElementResult = operations.CloneElementResult;
export const cloneElement = operations.cloneElement;
export type SetElementAnimationParams = operations.SetElementAnimationParams;
export const setElementAnimation = operations.setElementAnimation;
export type GroupElementsParams = operations.GroupElementsParams;
export type GroupElementsResult = operations.GroupElementsResult;
export const groupElements = operations.groupElements;
export type UngroupElementsParams = operations.UngroupElementsParams;
export type UngroupElementsResult = operations.UngroupElementsResult;
export const ungroupElements = operations.ungroupElements;
export type BatchUpdateElementsParams = operations.BatchUpdateElementsParams;
export const batchUpdateElements = operations.batchUpdateElements;
