// Compatibility exports: all document operations are owned by OOXML core.
import { apiToolsSlideTools as operations } from 'ooxml-core/pptx/automation';
export type GetSlideResult = operations.GetSlideResult;
export const getSlide = operations.getSlide;
export type AddSlideParams = operations.AddSlideParams;
export type AddSlideResult = operations.AddSlideResult;
export const addSlide = operations.addSlide;
export type DeleteSlidesParams = operations.DeleteSlidesParams;
export type DeleteSlidesResult = operations.DeleteSlidesResult;
export const deleteSlides = operations.deleteSlides;
export type ReorderSlidesParams = operations.ReorderSlidesParams;
export const reorderSlides = operations.reorderSlides;
export type DuplicateSlideParams = operations.DuplicateSlideParams;
export const duplicateSlide = operations.duplicateSlide;
export type UpdateSlidePropertiesParams = operations.UpdateSlidePropertiesParams;
export const updateSlideProperties = operations.updateSlideProperties;
export type SetSlideTransitionParams = operations.SetSlideTransitionParams;
export const setSlideTransition = operations.setSlideTransition;
export type SetCanvasSizeParams = operations.SetCanvasSizeParams;
export const setCanvasSize = operations.setCanvasSize;
