/* oxlint-disable vitest/prefer-importing-vitest-globals -- Playwright spec, `test`/`expect` come from @playwright/test */
/**
 * A real-world deck's slide 12 rendered its picture-filled trapezoid upside
 * down in this viewer, but right-side up in real PowerPoint. The shape was a
 * `<p:sp>` with a `flipV="1"` `a:custGeom` outline, filled by `a:blipFill`
 * whose `@rotWithShape="0"` explicitly tells a renderer to keep the PICTURE
 * fixed to the page frame while only the shape's own GEOMETRY (its outline)
 * rotates/flips. Every binding was applying the shape's flip transform to the
 * whole element, picture included, because a CSS `background-image` (or an
 * `<img>` with no transform of its own) has no independent orientation from
 * its container.
 *
 * `image-fill-rot-with-shape.pptx` (generated by
 * `generate-image-fill-rot-with-shape-fixture.ts`) reproduces just the
 * construct: two flipped trapezoids filled with the same picture, one with
 * `rotWithShape="0"` and one without (the control, at the schema default of
 * `true`). Asserting the COMPUTED `transform` of each shape's `<img>` is
 * deliberate, matching `line-fill-parity.spec.ts`: it is an exact, unit-free
 * fact every binding must agree on, and it is what `pptx-viewer-shared`'s
 * `getImageFillCounterTransform` decides.
 *
 * Run: bunx playwright test image-fill-rot-with-shape
 */
import { expect, test } from '@playwright/test';

import { fixture, loadDeckAt } from './support/deck';
import { acrossFrameworks } from './support/parity';

const DECK = fixture('image-fill-rot-with-shape.pptx');

interface ImgFacts {
	/** The trapezoid shape's own computed `transform` (its geometry/outline). */
	containerTransform: string;
	/** The picture content layer's (`<img>`) computed `transform`. */
	imgTransform: string;
}

test.describe('cross-binding a:blipFill/@rotWithShape on a shape-filled-by-picture', () => {
	test('the picture stays upright while the shape outline still flips', async ({
		browser,
	}, testInfo) => {
		test.slow();

		const results = await acrossFrameworks(browser, testInfo, async (page, origin) => {
			await loadDeckAt(page, origin, DECK);
			return page.evaluate(() => {
				const nodes = [
					...document.querySelectorAll('[data-pptx-viewport] [data-element-id]'),
				] as HTMLElement[];
				return nodes.map((node) => {
					const img = node.querySelector('img');
					return {
						containerTransform: getComputedStyle(node).transform,
						imgTransform: img ? getComputedStyle(img).transform : 'none',
					} satisfies ImgFacts;
				});
			});
		});

		expect(results.length).toBeGreaterThan(1);

		// Every binding must see the same two shapes, in the same order.
		for (const result of results) {
			expect(result.value, `${result.framework.name} element count`).toHaveLength(2);
		}

		const [reference, ...rest] = results;
		for (const other of rest) {
			expect(other.value, `${other.framework.name} vs ${reference.framework.name}`).toStrictEqual(
				reference.value,
			);
		}

		const [rotWithShapeFalse, rotWithShapeDefault] = reference.value;

		// Both trapezoids' OWN geometry still flips vertically: `flipV="1"` is
		// unconditional on the shape, `rotWithShape` only governs the FILL.
		// `scaleY(-1)` is `matrix(1, 0, 0, -1, 0, 0)`.
		expect(rotWithShapeFalse.containerTransform).toBe('matrix(1, 0, 0, -1, 0, 0)');
		expect(rotWithShapeDefault.containerTransform).toBe('matrix(1, 0, 0, -1, 0, 0)');

		// `rotWithShape="0"`: the picture's own content layer must carry the
		// EXACT inverse of the container's flip, so the two cancel out and the
		// bitmap renders upright (this is the reported bug: it used to be
		// 'none', so the picture flipped along with the outline).
		expect(rotWithShapeFalse.imgTransform).toBe('matrix(1, 0, 0, -1, 0, 0)');

		// The control shape (no `@rotWithShape`, schema default `true`) must be
		// completely unaffected by this fix: its picture has no transform of its
		// own and simply inherits the container's flip, exactly as before.
		expect(rotWithShapeDefault.imgTransform).toBe('none');
	});
});
