/* oxlint-disable vitest/prefer-importing-vitest-globals -- Playwright spec, `test`/`expect` come from @playwright/test */
/**
 * Merge Shapes and the on-canvas picture crop, end to end in every binding.
 *
 * The decisions live in `packages/shared/src/render/merge-shapes` and
 * `packages/shared/src/render/picture-crop`; the unit suites pin those and each
 * binding's wiring. This spec proves the part they cannot: that each demo's
 * ribbon, context menu and crop overlay are actually wired to them, that the
 * result is ONE undo step, and that it saves as real OOXML (`a:custGeom` for a
 * merge, `a:srcRect` for a crop).
 *
 * Fixture: `merge-crop.pptx` (generated by
 * `fixtures/generate-merge-crop-fixture.ts`): "Merge A" (red rectangle),
 * "Merge B" (blue ellipse overlapping it) and the picture "Crop Pic".
 *
 * Run: PPTX_E2E_PORT_OFFSET=100 bunx playwright test merge-shapes-crop --project=react
 */
import { expect, test } from '@playwright/test';
import type { Locator, Page } from '@playwright/test';

import { savePptxViaBackstage } from './save-pptx';
import { chooseCommand, marqueeAcross, openMenuOn } from './support/context-menu';
import {
	elementsOfType,
	elementWithText,
	fixture,
	loadDeck,
	selectElement,
	slideElements,
	slideStage,
} from './support/deck';
import { downloadBytes } from './support/exports';
import { pressShortcut } from './support/keyboard';
import { extractElementBlock, readZipPartText } from './support/pptx-xml';

test.use({ viewport: { width: 1440, height: 900 } });

const DECK = fixture('merge-crop.pptx');
const MERGE_LABELS = [
	'union shapes',
	'combine shapes',
	'fragment shapes',
	'intersect shapes',
	'subtract shapes',
];

function control(page: Page, id: string): Locator {
	return page.locator(`[data-pptx-ribbon-control="${id}"]:visible`).first();
}

function picture(page: Page): Locator {
	return elementsOfType(page, 'image').first();
}

function cropOverlay(page: Page): Locator {
	return page.locator('[data-pptx-crop-overlay="true"]');
}

async function openDeck(page: Page, path = '/'): Promise<void> {
	await loadDeck(page, DECK, path);
	await elementWithText(page, 'Merge B').waitFor();
	await page.waitForTimeout(300);
}

async function selectBothShapes(page: Page): Promise<void> {
	await marqueeAcross(page, slideStage(page), [
		elementWithText(page, 'Merge A'),
		elementWithText(page, 'Merge B'),
	]);
}

async function dragBy(page: Page, target: Locator, dx: number, dy: number): Promise<void> {
	const box = await target.boundingBox();
	if (!box) {
		throw new Error('drag target is not laid out');
	}
	const x = box.x + box.width / 2;
	const y = box.y + box.height / 2;
	await page.mouse.move(x, y);
	await page.mouse.down();
	await page.mouse.move(x + dx / 2, y + dy / 2, { steps: 5 });
	await page.mouse.move(x + dx, y + dy, { steps: 5 });
	await page.mouse.up();
	await page.waitForTimeout(250);
}

async function pictureWidth(page: Page): Promise<number> {
	return (await picture(page).boundingBox())?.width ?? 0;
}

async function enterCropMode(page: Page): Promise<void> {
	await selectElement(page, picture(page));
	await control(page, 'crop').click();
	await expect(cropOverlay(page)).toBeVisible();
}

test.describe('Merge Shapes', () => {
	test('Union from the ribbon makes one red freeform that saves as a:custGeom and undoes in one step', async ({
		page,
	}) => {
		await openDeck(page);
		await expect(slideElements(page)).toHaveCount(3);
		await expect(control(page, 'merge-shapes')).toBeDisabled();

		await selectBothShapes(page);
		await expect(control(page, 'merge-shapes')).toBeEnabled();
		await control(page, 'merge-shapes').click();
		await page.locator('[data-pptx-merge-op="union"]:visible').first().click();

		await expect(slideElements(page)).toHaveCount(2);
		await expect(elementWithText(page, 'Merge A')).toBeVisible();
		await expect(slideElements(page).filter({ hasText: 'Merge B' })).toHaveCount(0);

		const bytes = await downloadBytes(await savePptxViaBackstage(page));
		const slideXml = await readZipPartText(bytes, 'ppt/slides/slide1.xml');
		const merged = extractElementBlock(slideXml, 'p:sp', 'Merge A');
		expect(merged).toContain('<a:custGeom>');
		expect(merged).toContain('<a:pathLst>');
		expect(merged).not.toContain('<a:prstGeom');
		expect(merged).toContain('C00000');
		expect(slideXml).not.toContain('Merge B');

		await pressShortcut(page, 'Control+z');
		await expect(slideElements(page)).toHaveCount(3);
	});

	test('the context menu offers all five operations and Fragment splits into three pieces', async ({
		page,
	}) => {
		await openDeck(page);
		await selectBothShapes(page);
		const menu = await openMenuOn(page, elementWithText(page, 'Merge B'));
		expect(menu.present).toBeTruthy();
		for (const label of MERGE_LABELS) {
			expect(menu.labels, `context menu offers "${label}"`).toContain(label);
		}
		await chooseCommand(page, 'Fragment Shapes');
		// Three fragments plus the untouched picture.
		await expect(slideElements(page)).toHaveCount(4);
	});
});

test.describe('Picture crop', () => {
	test('dragging a crop handle crops live, Enter commits one undo step and saves a:srcRect', async ({
		page,
	}) => {
		await openDeck(page);
		const before = await pictureWidth(page);
		await enterCropMode(page);
		await expect(page.locator('[data-pptx-crop-handle]')).toHaveCount(8);

		await dragBy(page, page.locator('[data-pptx-crop-handle="w"]').first(), 80, 0);
		await page.keyboard.press('Enter');
		await expect(cropOverlay(page)).toHaveCount(0);
		const after = await pictureWidth(page);
		expect(after).toBeLessThan(before - 20);

		const bytes = await downloadBytes(await savePptxViaBackstage(page));
		const slideXml = await readZipPartText(bytes, 'ppt/slides/slide1.xml');
		const pic = extractElementBlock(slideXml, 'p:pic', 'Crop Pic');
		expect(pic).toMatch(/<a:srcRect[^>]*\bl="[1-9]\d*"/u);

		await pressShortcut(page, 'Control+z');
		await expect.poll(() => pictureWidth(page)).toBeGreaterThan(before - 2);
	});

	test('Escape cancels the crop and restores the picture', async ({ page }) => {
		await openDeck(page);
		const before = await pictureWidth(page);
		await enterCropMode(page);
		await dragBy(page, page.locator('[data-pptx-crop-handle="e"]').first(), -80, 0);
		expect(await pictureWidth(page)).toBeLessThan(before - 20);
		await page.keyboard.press('Escape');
		await expect(cropOverlay(page)).toHaveCount(0);
		await expect.poll(() => pictureWidth(page)).toBeGreaterThan(before - 2);
	});

	test('Crop to Aspect Ratio 1:1 squares the picture frame', async ({ page }) => {
		await openDeck(page);
		await selectElement(page, picture(page));
		await control(page, 'crop-menu').click();
		await page.locator('[data-pptx-crop-aspect="1:1"]:visible').first().click();
		await expect
			.poll(async () => {
				const box = await picture(page).boundingBox();
				return box ? Math.abs(box.width - box.height) : Number.POSITIVE_INFINITY;
			})
			.toBeLessThan(3);
	});

	test('the context menu offers Crop on a picture', async ({ page }) => {
		await openDeck(page);
		await selectElement(page, picture(page));
		const menu = await openMenuOn(page, picture(page));
		expect(menu.labels).toContain('crop');
		await chooseCommand(page, 'Crop');
		await expect(cropOverlay(page)).toBeVisible();
	});
});

test('a host can hide both controls through the customisation model', async ({ page }) => {
	const customization = { ribbon: { hiddenButtons: ['mergeShapes', 'crop'] } };
	await openDeck(page, `/?customization=${encodeURIComponent(JSON.stringify(customization))}`);
	await expect(page.locator('[data-pptx-ribbon-control="merge-shapes"]')).toHaveCount(0);
	await expect(page.locator('[data-pptx-ribbon-control="crop"]')).toHaveCount(0);
});
