/* oxlint-disable vitest/prefer-importing-vitest-globals -- Playwright spec, `test`/`expect` come from @playwright/test */
/**
 * The read-only recommendation banner's modify-password unlock prompt for a
 * SALT-LESS `p:modifyVerifier` (no `saltData` attribute at all), driven the
 * same way in all five demos.
 *
 * `modify-password-saltless.pptx` (see `fixtures/modify-password-saltless.pptx`,
 * generated by `scripts/make-saltless-verifier-fixture.mjs`) carries a REAL
 * SHA-512 hash for the password `open sesame`, checkable per the ECMA-376
 * derivation, but no `saltData` attribute. `saltData` is optional per
 * ECMA-376 19.2.1.22; core's `verifyModifyPassword` treats a missing salt as
 * zero-length rather than refusing to check the hash (see that module's doc
 * comment, "Salt-less verifiers"). Before this fix, a salt-less verifier fell
 * back to an unconditional "Edit anyway" with no password prompt at all; this
 * spec is the regression test for that fallback being gone.
 *
 * This deck is synthetic: real PowerPoint always writes a salt (COM-confirmed),
 * and separately, COM testing showed real PowerPoint's own "Set Password to
 * Modify" check rejects EVERY password (including the mathematically correct
 * one) for a hand-authored salt-less verifier - see `verifyModifyPassword`'s
 * module doc comment for the full finding. This spec pins THIS viewer's own,
 * spec-conformant behaviour, not a claim that PowerPoint would accept this
 * file's password too.
 *
 * Every locator is a `data-testid` from the shared banner contract
 * (`packages/shared/src/render/read-only-recommendation.ts` +
 * `checkModifyPassword`), so a binding that renders the prompt with a
 * different hook is a parity bug in that binding, not a reason to add a
 * fallback here.
 *
 * Run: bunx playwright test modify-password-saltless
 */
import { expect, test } from '@playwright/test';

import { fixture, loadDeck } from './support/deck';

const SALTLESS_DECK = fixture('modify-password-saltless.pptx');
const CORRECT_PASSWORD = 'open sesame';

test.describe('modify-password unlock prompt (salt-less verifier)', () => {
	test('a salt-less modifyVerifier hash shows the banner and requires a password', async ({
		page,
	}) => {
		await loadDeck(page, SALTLESS_DECK);

		const banner = page.getByTestId('pptx-readonly-banner');
		await expect(banner).toBeVisible();
		await expect(banner).toHaveAttribute('data-kind', 'modifyVerifier');

		// "Edit anyway" opens the password prompt instead of unlocking
		// immediately: a missing saltData must NOT fall back to an
		// unconditional unlock.
		await page.getByTestId('pptx-readonly-edit-anyway').click();
		await expect(page.getByTestId('pptx-readonly-password-form')).toBeVisible();
		await expect(banner).toBeVisible();
	});

	test('a wrong password stays read-only and reports the error', async ({ page }) => {
		await loadDeck(page, SALTLESS_DECK);
		await page.getByTestId('pptx-readonly-edit-anyway').click();

		const input = page.getByTestId('pptx-readonly-password-input');
		await expect(input).toBeVisible();
		await input.fill('definitely-wrong');
		await page.getByTestId('pptx-readonly-unlock').click();

		await expect(page.getByTestId('pptx-readonly-password-error')).toBeVisible();
		// Still locked: the form (not the edit-anyway/dismiss pair) is still up,
		// and the banner itself never went away.
		await expect(page.getByTestId('pptx-readonly-password-form')).toBeVisible();
		await expect(page.getByTestId('pptx-readonly-banner')).toBeVisible();
	});

	test('the correct password unlocks editing and closes the prompt', async ({ page }) => {
		await loadDeck(page, SALTLESS_DECK);
		await page.getByTestId('pptx-readonly-edit-anyway').click();

		const input = page.getByTestId('pptx-readonly-password-input');
		await input.fill(CORRECT_PASSWORD);
		await page.getByTestId('pptx-readonly-unlock').click();

		// Unmounted or hidden are both fine (see `modify-password-prompt.spec.ts`):
		// a binding may keep the node and toggle `hidden` rather than tear it down.
		await expect(page.getByTestId('pptx-readonly-banner')).toBeHidden();
	});
});
