/**
 * Loads the real, on-disk salt-less `p:modifyVerifier` fixtures (generated by
 * `scripts/make-saltless-verifier-fixture.mjs`, password "open sesame") for
 * every algorithm family this codebase digests, and confirms the full
 * load -> extract -> verify path works end to end, not just the in-memory
 * `PptxModifyVerifier` objects `modify-verifier.test.ts` builds directly.
 *
 * This is the fixture COM was used to confirm real PowerPoint itself accepts
 * and enforces (see `modify-verifier.ts`'s module doc comment,
 * "Salt-less verifiers"); this test pins the same file our own loader parses.
 *
 * @module modify-verifier-saltless-fixture.test
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { PptxHandler } from '../PptxHandler';
import { verifyModifyPassword } from './modify-verifier';

const PASSWORD = 'open sesame';

function fixtureBytes(name: string): Uint8Array {
	const path = fileURLToPath(new URL(`../../__tests__/fixtures/${name}`, import.meta.url));
	return new Uint8Array(readFileSync(path));
}

describe('salt-less modifyVerifier fixtures (packages/core/src/__tests__/fixtures)', () => {
	it('modify-verifier-saltless.pptx (SHA-512): parses with hashData and no saltData, verifies the password', async () => {
		const handler = new PptxHandler();
		const data = await handler.load(fixtureBytes('modify-verifier-saltless.pptx').buffer);
		expect(data.modifyVerifier?.hashData).toBeTruthy();
		expect(data.modifyVerifier?.saltData).toBeUndefined();
		expect(data.modifyVerifier?.algorithmName).toBe('SHA-512');
		await expect(verifyModifyPassword(data.modifyVerifier!, PASSWORD)).resolves.toBeTruthy();
		await expect(verifyModifyPassword(data.modifyVerifier!, 'wrong')).resolves.toBeFalsy();
	});

	it.each([
		['modify-verifier-saltless-sha1.pptx', 'SHA-1'],
		['modify-verifier-saltless-sha256.pptx', 'SHA-256'],
		['modify-verifier-saltless-sha384.pptx', 'SHA-384'],
		['modify-verifier-saltless-md5.pptx', 'MD5'],
		['modify-verifier-saltless-ripemd160.pptx', 'RIPEMD-160'],
		['modify-verifier-saltless-whirlpool.pptx', 'WHIRLPOOL'],
	])(
		'%s: parses with no saltData and verifies the password',
		async (file, algorithmName) => {
			const handler = new PptxHandler();
			const data = await handler.load(fixtureBytes(file).buffer);
			expect(data.modifyVerifier?.saltData).toBeUndefined();
			expect(data.modifyVerifier?.algorithmName).toBe(algorithmName);
			await expect(verifyModifyPassword(data.modifyVerifier!, PASSWORD)).resolves.toBeTruthy();
			await expect(verifyModifyPassword(data.modifyVerifier!, 'wrong')).resolves.toBeFalsy();
		},
		// WHIRLPOOL is a pure-TypeScript digest (no Web Crypto implementation);
		// 100000 spin-count iterations of it take longer than the default 30s.
		60_000,
	);
});
