<script lang="ts">
	import type { PptxChartData, PptxChartType } from 'pptx-viewer-core'; import type { EditorState } from '../../editor/editor-state.svelte';
	const { editor }: { editor: EditorState } = $props(); const chart=$derived(editor.selectedElement?.type==='chart'?editor.selectedElement:undefined); const data=$derived(chart?.chartData);
	function patch(next:Partial<PptxChartData>):void{if(chart&&data)editor.applyElementPatch(chart.id,{chartData:{...data,...next}})}
	function seriesPatch(index:number,next:Record<string,unknown>):void{if(!data)return;patch({series:data.series.map((s,i)=>i===index?{...s,...next}:s)})}
	function axisPatch(index:number,next:Record<string,unknown>):void{if(!data)return;patch({axes:(data.axes??[]).map((axis,i)=>i===index?{...axis,...next}:axis)})}
</script>
{#if data}<div class="section"><label>Chart type<select value={data.chartType} onchange={(e)=>patch({chartType:e.currentTarget.value as PptxChartType})}>{#each ['bar','line','pie','doughnut','area','scatter','bubble','radar','waterfall','funnel','treemap','sunburst','combo'] as type}<option value={type}>{type}</option>{/each}</select></label><label>Title<input value={data.title??''} oninput={(e)=>patch({title:e.currentTarget.value,style:{...data.style,hasTitle:Boolean(e.currentTarget.value)}})} /></label><div class="checks"><label><input type="checkbox" checked={data.style?.hasLegend??false} onchange={(e)=>patch({style:{...data.style,hasLegend:e.currentTarget.checked}})} />Legend</label><label><input type="checkbox" checked={data.style?.hasDataLabels??false} onchange={(e)=>patch({style:{...data.style,hasDataLabels:e.currentTarget.checked}})} />Data labels</label><label><input type="checkbox" checked={data.style?.hasGridlines??false} onchange={(e)=>patch({style:{...data.style,hasGridlines:e.currentTarget.checked}})} />Gridlines</label></div><h5>Series</h5>{#each data.series as series,index}<fieldset><input aria-label="Series name" value={series.name} oninput={(e)=>seriesPatch(index,{name:e.currentTarget.value})} /><input aria-label="Series values" value={series.values.join(', ')} onchange={(e)=>seriesPatch(index,{values:e.currentTarget.value.split(',').map(Number).filter(Number.isFinite)})} /><input type="color" aria-label="Series color" value={series.color??'#4472c4'} onchange={(e)=>seriesPatch(index,{color:e.currentTarget.value})} /><select aria-label="Trendline" value={series.trendlines?.[0]?.trendlineType??''} onchange={(e)=>seriesPatch(index,{trendlines:e.currentTarget.value?[{trendlineType:e.currentTarget.value}]:[]})}><option value="">No trendline</option>{#each ['linear','exponential','logarithmic','polynomial','power','movingAvg'] as type}<option value={type}>{type}</option>{/each}</select></fieldset>{/each}<h5>Axes</h5>{#each data.axes??[] as axis,index}<fieldset><input aria-label="Axis title" value={axis.titleText??''} oninput={(e)=>axisPatch(index,{titleText:e.currentTarget.value})} /><input type="number" aria-label="Axis minimum" placeholder="Min" value={axis.min??''} onchange={(e)=>axisPatch(index,{min:e.currentTarget.value===''?undefined:Number(e.currentTarget.value)})} /><input type="number" aria-label="Axis maximum" placeholder="Max" value={axis.max??''} onchange={(e)=>axisPatch(index,{max:e.currentTarget.value===''?undefined:Number(e.currentTarget.value)})} /></fieldset>{/each}</div>{/if}
<style>.section{display:grid;gap:8px}label{display:grid;gap:3px;color:var(--pptx-muted-foreground);font-size:10px}input,select{min-width:0;height:26px;border:1px solid var(--pptx-border);border-radius:5px;background:var(--pptx-background);color:inherit}.checks{display:grid;grid-template-columns:1fr 1fr;gap:5px}.checks label{display:flex;align-items:center}h5{margin:6px 0 0;font-size:10px;text-transform:uppercase}fieldset{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:0;padding:7px;border:1px solid var(--pptx-border);border-radius:6px}</style>
