/**
 * Legacy PowerPoint 97-2003 "shade to title colour" background effect.
 *
 * `<p:bgPr shadeToTitle="1">` (ECMA-376 Part 1, Section19.3.1.2,
 * `CT_BackgroundProperties`) marks a slide's background gradient to shade
 * toward the title placeholder's text colour. It was exposed in the
 * PowerPoint 97-2003 "Background" dialog's two-colour shaded-fill picker as a
 * "Shade to title color" checkbox; no PowerPoint version since 2007 exposes a
 * UI control that writes it, and it has never been observed in this
 * project's real-world corpus (see `docs/guide/limitations.md`).
 *
 * No published ECMA-376 or MS-ODRAWXML text documents the exact resulting
 * blend, so {@link shadeGradientTowardTitle} is a best-reasoned
 * approximation rather than a byte-for-byte match of legacy PowerPoint's
 * renderer: it recolours the gradient's LAST stop (the one nearest the edge
 * of the slide, opposite the direction the gradient starts from) to the
 * title's resolved text colour, preserving that stop's position and alpha
 * and leaving every other stop, the gradient type, and its angle/shape
 * untouched. This reflects the flag's documented intent ("shade background
 * TOWARD the title colour") without a documented ground truth to verify the
 * exact stop position, interpolation curve, or how many stops legacy
 * PowerPoint actually touched.
 *
 * Pure, framework-agnostic, and consumed by every binding through
 * {@link getSlideBackgroundStyle} in `slide-background.ts`, so the effect is
 * decided once here rather than ported five times (see CLAUDE.md Rule 2).
 *
 * @module render/background-shade-to-title
 */
import type { PptxSlide } from 'pptx-viewer-core';
import { hasTextProperties } from 'pptx-viewer-core';

import { colorWithOpacity, normalizeHexColor } from './fill-style';
import { resolveSlideOutlineElements } from './outline-view';

/**
 * Resolve the effective colour of a slide's title, for use by
 * {@link shadeGradientTowardTitle}.
 *
 * Reuses {@link resolveSlideOutlineElements}'s title resolution (title/ctrTitle
 * placeholder first, falling back to the slide's first text-bearing element
 * when the deck carries no placeholders at all) rather than re-implementing
 * placeholder-type detection here: both features agree on what "the slide's
 * title" means, and that decision should not drift between them.
 *
 * Returns `undefined` when the slide has no title, or the title carries no
 * resolved colour anywhere in its runs.
 */
export function resolveTitleColorForShading(slide: PptxSlide | undefined): string | undefined {
	if (!slide) {
		return undefined;
	}
	const title = resolveSlideOutlineElements(slide).title;
	if (!title || !hasTextProperties(title)) {
		return undefined;
	}

	for (const segment of title.textSegments ?? []) {
		const color = segment.style?.color;
		if (typeof color === 'string' && color.trim().length > 0) {
			return color;
		}
	}

	const flatColor = title.textStyle?.color;
	return typeof flatColor === 'string' && flatColor.trim().length > 0 ? flatColor : undefined;
}

interface ParsedCssGradient {
	fn: 'linear-gradient' | 'radial-gradient';
	/** Angle/shape/position preamble before the stop list, when present. */
	header: string | undefined;
	stops: string[];
}

/** Split a CSS function's argument list on commas, ignoring ones nested inside `fn(...)`. */
function splitTopLevel(input: string): string[] {
	const tokens: string[] = [];
	let depth = 0;
	let start = 0;
	for (let i = 0; i < input.length; i++) {
		const ch = input[i];
		if (ch === '(') {
			depth++;
		} else if (ch === ')') {
			depth--;
		} else if (ch === ',' && depth === 0) {
			tokens.push(input.slice(start, i));
			start = i + 1;
		}
	}
	tokens.push(input.slice(start));
	return tokens;
}

/** Matches the `<angle>` (or `to <side>`) preamble `buildGradientCssFromStops` emits for linear gradients. */
function isLinearHeader(token: string): boolean {
	const trimmed = token.trim();
	return /^-?\d+(?:\.\d+)?deg$/u.test(trimmed) || /^to\s+(top|bottom|left|right)/iu.test(trimmed);
}

/** Matches the `<shape> at <x> <y>` preamble `buildGradientCssFromStops` emits for radial gradients. */
function isRadialHeader(token: string): boolean {
	return /\bat\b/u.test(token);
}

/**
 * Parse a `linear-gradient(...)` / `radial-gradient(...)` CSS string produced
 * by this project's own gradient codec back into a header + stop list.
 *
 * Deliberately narrow: it understands exactly the shapes
 * `buildGradientCssFromStops` (`packages/core`) emits, not arbitrary
 * author-supplied CSS, since the only input this function ever sees is a
 * slide's own `backgroundGradient`, generated by that same codec.
 */
function parseCssGradient(css: string): ParsedCssGradient | undefined {
	const match = /^(linear-gradient|radial-gradient)\((.*)\)$/su.exec(css.trim());
	if (!match) {
		return undefined;
	}
	const fn = match[1] as ParsedCssGradient['fn'];
	const tokens = splitTopLevel(match[2]).map((token) => token.trim());
	if (tokens.length === 0 || tokens[0] === undefined) {
		return undefined;
	}

	const hasHeader =
		fn === 'linear-gradient' ? isLinearHeader(tokens[0]) : isRadialHeader(tokens[0]);
	const header = hasHeader ? tokens[0] : undefined;
	const stops = hasHeader ? tokens.slice(1) : tokens;
	if (stops.length === 0) {
		return undefined;
	}
	return { fn, header, stops };
}

/** Trailing ` <n>%` position suffix `buildGradientCssFromStops` appends to a stop's colour token. */
const STOP_POSITION_RE = /\s+(\d+(?:\.\d+)?%)\s*$/u;
const RGBA_RE = /^rgba\(\s*[\d.]+\s*,\s*[\d.]+\s*,\s*[\d.]+\s*,\s*([\d.]+)\s*\)$/u;

/** Recolour one gradient stop token to `titleColor`, preserving its position and alpha. */
function recolorStop(stop: string, titleColor: string): string {
	const positionMatch = STOP_POSITION_RE.exec(stop);
	const position = positionMatch?.[1];
	const colorPart = positionMatch ? stop.slice(0, stop.length - positionMatch[0].length) : stop;

	const alphaMatch = RGBA_RE.exec(colorPart.trim());
	const normalizedTitle = normalizeHexColor(titleColor, titleColor);
	const newColor = alphaMatch
		? colorWithOpacity(normalizedTitle, Number.parseFloat(alphaMatch[1]))
		: normalizedTitle;

	return position ? `${newColor} ${position}` : newColor;
}

/**
 * Apply the legacy "shade to title colour" adjustment to a slide's background
 * CSS gradient. See the module docstring for the approximation this makes.
 *
 * Returns `gradientCss` unchanged when there is no title colour to shade
 * toward, or when the string is not a gradient this module's parser
 * recognises (an unresolved fill, or a future gradient shape the codec does
 * not yet emit): silently doing nothing is the safe failure mode for a
 * decorative legacy hint, matching how {@link resolveTitleColorForShading}
 * already returns `undefined` rather than throwing.
 */
export function shadeGradientTowardTitle(
	gradientCss: string | undefined,
	titleColor: string | undefined,
): string | undefined {
	if (!gradientCss || !titleColor) {
		return gradientCss;
	}
	const parsed = parseCssGradient(gradientCss);
	if (!parsed) {
		return gradientCss;
	}

	const stops = [...parsed.stops];
	const lastIndex = stops.length - 1;
	stops[lastIndex] = recolorStop(stops[lastIndex], titleColor);

	const args = parsed.header ? [parsed.header, ...stops] : stops;
	return `${parsed.fn}(${args.join(', ')})`;
}
