/** Compatibility entry: canonical equation logic lives in ooxml-core/math. */
export {
	GREEK_MAP,
	OPERATOR_MAP,
	ESCAPE_MAP,
	NARY_MAP,
	FUNC_NAMES,
	LIMIT_FUNC_NAMES,
	ACCENT_MAP,
	ACCENT_ALIASES,
	DELIM_MAP,
	MATRIX_ENVS,
	EQARR_ENVS,
	REVERSE_GREEK,
	REVERSE_OPERATOR,
	REVERSE_NARY,
	REVERSE_ACCENT,
	REVERSE_DELIM,
	REVERSE_ESCAPE,
} from 'pptx-viewer-core/math';
