/**
 * table-style-builtins.test.ts - regression coverage for the built-in
 * catalogue's `a:alpha` fields.
 *
 * The catalogue in table-style-builtins-data.ts was generated by parsing a
 * real PowerPoint-produced `ppt/tableStyles.xml` with core's own
 * `parseTableStyleList` (see that file's module docblock). At the time it was
 * generated, `table-style-fill-parse.ts` / `table-style-border-parse.ts`
 * parsed only `a:tint`/`a:shade` off a fill's `a:schemeClr`, so
 * `<a:schemeClr val="accent1"><a:alpha val="20000"/></a:schemeClr>` silently
 * lost its alpha and the generated catalogue baked in a fully opaque band
 * fill. "Light Style 1", "Light Style 3", "Themed Style 1", and "Themed Style
 * 2" all band with a 20-40% transparent tint of the theme colour in real
 * PowerPoint (confirmed against `ppt/tableStyles.xml` from a deck built over
 * COM with `Table.ApplyStyle` for each of these styles), not an opaque one.
 */
import { describe, expect, it } from 'vitest';

import { getBuiltinTableStyle } from './table-style-builtins';

describe('built-in table style catalogue - a:alpha bands', () => {
	it('bands "Light Style 1 - Accent 1" at 20% alpha, not opaque', () => {
		const style = getBuiltinTableStyle('{3B4B98B0-60AC-42C2-AFA5-B58CD77FA1E5}');
		expect(style?.band1HFill).toMatchObject({ schemeColor: 'accent1', alpha: 20_000 });
		expect(style?.band1VFill).toMatchObject({ schemeColor: 'accent1', alpha: 20_000 });
	});

	it('bands "Light Style 3 - Accent 1" at 20% alpha, not opaque', () => {
		const style = getBuiltinTableStyle('{BC89EF96-8CEA-46FF-86C4-4CE0E7609802}');
		expect(style?.band1HFill).toMatchObject({ schemeColor: 'accent1', alpha: 20_000 });
		expect(style?.band1VFill).toMatchObject({ schemeColor: 'accent1', alpha: 20_000 });
	});

	it('bands "Themed Style 1 - Accent 1" at 40% alpha, not opaque', () => {
		const style = getBuiltinTableStyle('{3C2FFA5D-87B4-456A-9821-1D502468CF0F}');
		expect(style?.band1HFill).toMatchObject({ schemeColor: 'accent1', alpha: 40_000 });
		expect(style?.band1VFill).toMatchObject({ schemeColor: 'accent1', alpha: 40_000 });
	});

	it('bands "Themed Style 2 - Accent 1" at 20% alpha over lt1, not opaque', () => {
		const style = getBuiltinTableStyle('{D113A9D2-9D6B-4929-AA2D-F23B5EE8CBE7}');
		expect(style?.band1HFill).toMatchObject({ schemeColor: 'lt1', alpha: 20_000 });
		expect(style?.band1VFill).toMatchObject({ schemeColor: 'lt1', alpha: 20_000 });
	});

	it('the base (non-accent) "Light Style 1" and "Light Style 3" also band at 20% alpha over tx1', () => {
		const lightStyle1 = getBuiltinTableStyle('{9D7B26C5-4107-4FEC-AEDC-1716B250A1EF}');
		expect(lightStyle1?.band1HFill).toMatchObject({ schemeColor: 'tx1', alpha: 20_000 });
		const lightStyle3 = getBuiltinTableStyle('{616DA210-FB5B-4158-B5E0-FEB733F419BA}');
		expect(lightStyle3?.band1HFill).toMatchObject({ schemeColor: 'tx1', alpha: 20_000 });
	});

	it('an accent substitution rewrites the scheme colour but keeps the alpha', () => {
		// "Light Style 1 - Accent 2" is derived from the Accent 1 template by
		// substituting the scheme colour key; the alpha must survive that swap.
		const style = getBuiltinTableStyle('{0E3FDE45-AF77-4B5C-9715-49D594BDF05E}');
		expect(style?.styleName).toBe('Light Style 1 - Accent 2');
		expect(style?.band1HFill).toMatchObject({ schemeColor: 'accent2', alpha: 20_000 });
	});

	it('a style with no authored alpha (Medium Style 2 - Accent 1) has none', () => {
		const style = getBuiltinTableStyle('{5C22544A-7EE6-4342-B048-85BDC9FD1C3A}');
		expect(style?.band1HFill?.alpha).toBeUndefined();
	});
});
