/**
 * GENERATED by scripts/gen-theme-variant-catalog.ts from Office's installed
 * Theme Fonts/*.xml (plus the built-in "Office" scheme first). Do not edit by hand.
 *
 * @module render/ribbon-galleries/theme-font-schemes-data
 */

/** [name, major (headings) latin typeface, minor (body) latin typeface]. */
export const THEME_FONT_SCHEME_ROWS: ReadonlyArray<readonly [string, string, string]> = [
	['Office', 'Aptos Display', 'Aptos'],
	['Office 2013 - 2022', 'Calibri Light', 'Calibri'],
	['Office 2007 - 2010', 'Cambria', 'Calibri'],
	['Arial', 'Arial', 'Arial'],
	['Arial Black-Arial', 'Arial Black', 'Arial'],
	['Arial-Times New Roman', 'Arial', 'Times New Roman'],
	['Calibri', 'Calibri', 'Calibri'],
	['Calibri Light-Constantia', 'Calibri Light', 'Constantia'],
	['Calibri-Cambria', 'Calibri', 'Cambria'],
	['Cambria', 'Cambria', 'Cambria'],
	['Candara', 'Candara', 'Candara'],
	['Century Gothic', 'Century Gothic', 'Century Gothic'],
	['Century Gothic-Palatino Linotype', 'Century Gothic', 'Palatino Linotype'],
	['Century Schoolbook', 'Century Schoolbook', 'Century Schoolbook'],
	['Consolas-Verdana', 'Consolas', 'Verdana'],
	['Constantia-Franklin Gothic Book', 'Constantia', 'Franklin Gothic Book'],
	['Corbel', 'Corbel', 'Corbel'],
	['Franklin Gothic', 'Franklin Gothic Medium', 'Franklin Gothic Book'],
	['Garamond', 'Garamond', 'Garamond'],
	['Garamond-TrebuchetMs', 'Garamond', 'Trebuchet MS'],
	['Georgia', 'Georgia', 'Georgia'],
	['Gill Sans MT', 'Gill Sans MT', 'Gill Sans MT'],
	['Times New Roman-Arial', 'Times New Roman', 'Arial'],
	['TrebuchetMs', 'Trebuchet MS', 'Trebuchet MS'],
	['Tw Cen MT', 'Tw Cen MT', 'Tw Cen MT'],
	['Tw Cen MT-Rockwell', 'Tw Cen MT', 'Rockwell'],
];
