/**
 * Regenerates the Design > Variants > Colors / Fonts catalogues
 * (packages/shared/src/render/ribbon-galleries/theme-*-schemes-data.ts) from
 * the scheme files Office installs:
 *
 *   C:\Program Files\Microsoft Office\root\Document Themes 16\Theme Colors\*.xml
 *   C:\Program Files\Microsoft Office\root\Document Themes 16\Theme Fonts\*.xml
 *
 *   bun scripts/gen-theme-variant-catalog.ts [<Document Themes 16 dir>]
 *
 * "Office" (the 2023+ default theme) is built into PowerPoint rather than
 * installed as a file; its values are the ones a new presentation reports via
 * COM (SlideMaster.Theme.ThemeColorScheme / ThemeFontScheme) and are written
 * first. The colour gallery keeps PowerPoint's hue order; fonts follow the
 * Office entries alphabetically.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.argv[2] ?? 'C:\\Program Files\\Microsoft Office\\root\\Document Themes 16';
const outDir = join(
	import.meta.dir,
	'..',
	'packages',
	'shared',
	'src',
	'render',
	'ribbon-galleries',
);

const SLOTS = [
	'dk1',
	'lt1',
	'dk2',
	'lt2',
	'accent1',
	'accent2',
	'accent3',
	'accent4',
	'accent5',
	'accent6',
	'hlink',
	'folHlink',
] as const;

const COLOR_ORDER = [
	'Office 2013 - 2022',
	'Office 2007 - 2010',
	'Grayscale',
	'Blue Warm',
	'Blue',
	'Blue II',
	'Blue Green',
	'Green',
	'Green Yellow',
	'Yellow',
	'Yellow Orange',
	'Orange',
	'Orange Red',
	'Red Orange',
	'Red',
	'Red Violet',
	'Violet',
	'Violet II',
	'Median',
	'Paper',
	'Marquee',
	'Slipstream',
	'Aspect',
];

const OFFICE_COLORS = [
	'000000',
	'FFFFFF',
	'0E2841',
	'E8E8E8',
	'156082',
	'E97132',
	'196B24',
	'0F9ED5',
	'A02B93',
	'4EA72E',
	'467886',
	'96607D',
];

function slotColor(xml: string, slot: string): string {
	const body = new RegExp(`<a:${slot}>(.*?)</a:${slot}>`, 'su').exec(xml)?.[1] ?? '';
	const value =
		/lastClr="([0-9A-Fa-f]{6})"/u.exec(body)?.[1] ?? /val="([0-9A-Fa-f]{6})"/u.exec(body)?.[1];
	if (!value) {
		throw new Error(`no ${slot} colour`);
	}
	return value.toUpperCase();
}

/** Display name: the file's basename (what the gallery shows), normalised. */
function displayName(file: string): string {
	return file.replace(/\.xml$/u, '');
}

const colorDir = join(root, 'Theme Colors');
const colors = new Map<string, string[]>();
for (const file of readdirSync(colorDir).filter((f) => f.endsWith('.xml'))) {
	const xml = readFileSync(join(colorDir, file), 'utf8');
	colors.set(
		displayName(file),
		SLOTS.map((slot) => slotColor(xml, slot)),
	);
}
const colorRows = [
	['Office', OFFICE_COLORS] as const,
	...COLOR_ORDER.map((name) => {
		const row = colors.get(name);
		if (!row) {
			throw new Error(`missing colour scheme ${name}`);
		}
		return [name, row] as const;
	}),
];
if (colorRows.length !== colors.size + 1) {
	throw new Error('unordered colour scheme on disk');
}

function latin(xml: string, group: 'majorFont' | 'minorFont'): string {
	const body = new RegExp(`<a:${group}>(.*?)</a:${group}>`, 'su').exec(xml)?.[1] ?? '';
	const face = /<a:latin typeface="([^"]*)"/u.exec(body)?.[1];
	if (!face) {
		throw new Error(`no ${group} latin`);
	}
	return face;
}

const fontDir = join(root, 'Theme Fonts');
const fontRows: Array<readonly [string, string, string]> = [];
for (const file of readdirSync(fontDir).filter((f) => f.endsWith('.xml'))) {
	const xml = readFileSync(join(fontDir, file), 'utf8');
	fontRows.push([displayName(file), latin(xml, 'majorFont'), latin(xml, 'minorFont')]);
}
const officeFirst = (name: string) => (name.startsWith('Office') ? `0${name}` : `1${name}`);
fontRows.sort((a, b) => officeFirst(a[0]).localeCompare(officeFirst(b[0])));
fontRows.sort(
	(a, b) => Number(b[0] === 'Office 2013 - 2022') - Number(a[0] === 'Office 2013 - 2022'),
);
fontRows.unshift(['Office', 'Aptos Display', 'Aptos']);

const header = (what: string, source: string) => `/**
 * GENERATED by scripts/gen-theme-variant-catalog.ts from Office's installed
 * ${source} (plus the built-in "Office" scheme first). Do not edit by hand.
 *
 * @module render/ribbon-galleries/${what}
 */
`;
const q = (s: string) => `'${s.replace(/'/gu, "\\'")}'`;

writeFileSync(
	join(outDir, 'theme-color-schemes-data.ts'),
	`${header('theme-color-schemes-data', 'Theme Colors/*.xml')}
/**
 * One row per scheme: [name, 'dk1 lt1 dk2 lt2 accent1..6 hlink folHlink'] (hex
 * without '#'), kept to one line each so the catalogue stays compact.
 */
const PACKED_ROWS: ReadonlyArray<readonly [string, string]> = [
${colorRows.map(([name, row]) => `\t[${q(name)}, ${q(row.join(' '))}],`).join('\n')}
];

/** [name, dk1, lt1, dk2, lt2, accent1..6, hlink, folHlink] (hex without '#'). */
export const THEME_COLOR_SCHEME_ROWS: ReadonlyArray<readonly [string, ...string[]]> =
	PACKED_ROWS.map(([name, hexes]) => [name, ...hexes.split(' ')] as const);
`,
);
writeFileSync(
	join(outDir, 'theme-font-schemes-data.ts'),
	`${header('theme-font-schemes-data', 'Theme Fonts/*.xml')}
/** [name, major (headings) latin typeface, minor (body) latin typeface]. */
export const THEME_FONT_SCHEME_ROWS: ReadonlyArray<readonly [string, string, string]> = [
${fontRows.map((row) => `\t[${row.map(q).join(', ')}],`).join('\n')}
];
`,
);
console.log(`wrote ${colorRows.length} colour schemes, ${fontRows.length} font schemes`);
