<script lang="ts">
	import type { RehearseState } from '../presentation/rehearse-state.svelte';
	import { useTranslator } from '../../i18n/context';

	const { rehearse, onsave, ondiscard }: { rehearse: RehearseState; onsave: () => void; ondiscard: () => void } = $props(); const t = useTranslator();
	const format = (ms: number) => new Date(ms).toISOString().slice(14, 19);
</script>
{#if rehearse.active}<div class="hud" role="status"><b>{t('pptx.rehearse.slide')} {rehearse.current + 1}</b><span>{format(rehearse.elapsedMs)}</span><button onclick={() => rehearse.togglePause()}>{t(rehearse.paused ? 'pptx.rehearse.resume' : 'pptx.rehearse.pause')}</button></div>{/if}
{#if rehearse.summaryOpen}<div class="backdrop"><!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role --><section role="dialog" tabindex="-1" aria-modal="true" aria-label={t('pptx.rehearse.summaryTitle')}><h2>{t('pptx.rehearse.summaryTitle')}</h2><div class="rows">{#each [...rehearse.times] as entry}<p><span>{t('pptx.rehearse.slide')} {entry[0] + 1}</span><b>{format(entry[1])}</b></p>{/each}<p class="total"><span>{t('pptx.rehearse.totalPresentationTime')}</span><b>{format(rehearse.totalMs)}</b></p></div><footer><button onclick={ondiscard}>{t('pptx.rehearse.discard')}</button><button class="primary" onclick={onsave}>{t('pptx.rehearse.saveTimings')}</button></footer></section></div>{/if}
<style>
	.hud{position:fixed;z-index:90;top:16px;left:50%;display:flex;align-items:center;gap:12px;padding:8px 12px;border:1px solid #ffffff33;border-radius:8px;background:#111d;color:#fff;transform:translateX(-50%);font-size:12px}.hud span{font:18px ui-monospace,monospace}.hud button,.backdrop button{border:1px solid var(--pptx-border,#3f3f52);border-radius:6px;padding:6px 10px;background:var(--pptx-muted,#2a2a3d);color:inherit}.backdrop{position:fixed;inset:0;z-index:1250;display:grid;place-items:center;background:#0009}.backdrop section{width:min(420px,calc(100vw - 32px));padding:20px;border:1px solid var(--pptx-border,#3f3f52);border-radius:12px;background:var(--pptx-card,#1e1e2e)}h2{margin:0 0 14px;font-size:15px}.rows{display:grid;gap:5px;max-height:300px;overflow:auto}.rows p{display:flex;justify-content:space-between;margin:0;padding:7px 9px;border-radius:5px;background:var(--pptx-muted,#2a2a3d);font-size:12px}.rows .total{margin-top:7px;border-top:1px solid var(--pptx-border,#3f3f52);font-weight:700}footer{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.backdrop .primary{background:var(--pptx-primary,#c43b32);color:#fff}
</style>
