import {
	createRibbonControlIcon,
	RIBBON_CONTROL_ICONS,
	galleryItemLabel,
	inlineGalleryItems,
} from '../render';
import type { RibbonGalleryDescriptor, RibbonGalleryItem } from '../render';
import { RIBBON_ICON_PATHS } from './ribbon-icons';
import { parseSvgPreview } from './safe-svg';

export type GalleryTranslate = (
	key: string,
	params?: Readonly<Record<string, string | number>>,
) => string;

/** All gallery markup is owned here; callers only supply shared descriptors and intents. */
export function createRibbonGalleryView(
	doc: Document,
	pick: (id: string) => void,
	toggle: () => void,
) {
	const root = doc.createElement('span');
	root.className = 'gallery-view';
	const strip = doc.createElement('div');
	strip.className = 'strip';
	const trigger = doc.createElement('button');
	trigger.type = 'button';
	trigger.className = 'trigger';
	trigger.setAttribute('data-pptx-compact', '');
	trigger.setAttribute('aria-haspopup', 'dialog');
	trigger.addEventListener('click', toggle);
	const popup = doc.createElement('div');
	popup.className = 'popup';
	popup.hidden = true;
	popup.setAttribute('role', 'dialog');
	root.append(strip, trigger);
	const caption = (t: GalleryTranslate, key: string, fallback: string) => {
		const translated = t(key);
		return translated && translated !== key ? translated : fallback;
	};
	const tile = (
		item: RibbonGalleryItem,
		width: number,
		height: number,
		disabled: boolean,
		t: GalleryTranslate,
	) => {
		const button = doc.createElement('button');
		button.type = 'button';
		button.className = 'tile';
		button.setAttribute('data-pptx-compact', '');
		button.dataset.galleryItem = item.id;
		button.disabled = disabled;
		button.setAttribute('aria-pressed', String(item.applied));
		button.setAttribute('aria-label', galleryItemLabel(item, t));
		button.title = galleryItemLabel(item, t);
		button.style.width = `${width + 6}px`;
		button.style.height = `${height + 6}px`;
		// Generated by the shared catalogue from trusted geometry and escaped theme data; still parsed
		// as an SVG document (no HTML sink) with anything executable stripped.
		const preview = parseSvgPreview(doc, item.previewSvg);
		if (preview) {
			button.append(preview);
		}
		button.addEventListener('click', () => pick(item.id));
		return button;
	};
	return {
		root,
		trigger,
		popup,
		clear() {
			strip.replaceChildren();
			popup.replaceChildren();
			trigger.removeAttribute('data-ribbon-gallery');
			trigger.removeAttribute('aria-label');
			trigger.textContent = '';
		},
		setOpen(open: boolean) {
			popup.hidden = !open;
			if (open) {
				root.append(popup);
			} else {
				popup.remove();
			}
		},
		paint(
			descriptor: RibbonGalleryDescriptor,
			t: GalleryTranslate,
			disabled: boolean,
			inline: boolean,
			chevronOnly: boolean,
			icon: string,
			open: boolean,
			controlId?: string,
		) {
			const title = caption(t, descriptor.labelKey, descriptor.label);
			trigger.dataset.ribbonGallery = descriptor.id;
			popup.dataset.ribbonGalleryPopup = descriptor.id;
			const more = t('pptx.gallery.more', { name: title });
			trigger.title = inline ? (more === 'pptx.gallery.more' ? `More ${title}` : more) : title;
			trigger.setAttribute('aria-label', trigger.title);
			trigger.disabled = disabled;
			trigger.replaceChildren();
			const command = descriptor.command;
			trigger.classList.toggle('command', Boolean(command));
			trigger.classList.toggle('command-large', Boolean(command?.large));
			if (command) {
				// A one-button command: no panel, no chevron; the tooltip says why it is off.
				trigger.removeAttribute('aria-haspopup');
				trigger.removeAttribute('aria-expanded');
				trigger.title = command.hintKey
					? caption(t, command.hintKey, command.hint ?? title)
					: title;
				trigger.setAttribute('aria-label', title);
				const svg = doc.createElementNS('http://www.w3.org/2000/svg', 'svg');
				svg.setAttribute('viewBox', '0 0 20 20');
				svg.setAttribute('aria-hidden', 'true');
				const path = doc.createElementNS(svg.namespaceURI, 'path');
				path.setAttribute('d', command.iconPath);
				svg.append(path);
				const label = doc.createElement('span');
				label.textContent = title;
				trigger.append(svg, label);
			} else if (!inline && !chevronOnly) {
				trigger.setAttribute('aria-haspopup', 'dialog');
				const svg =
					controlId && RIBBON_CONTROL_ICONS[controlId]
						? createRibbonControlIcon(doc, controlId)
						: doc.createElementNS('http://www.w3.org/2000/svg', 'svg');
				if (!svg.hasAttribute('viewBox')) {
					svg.setAttribute('viewBox', '0 0 20 20');
				}
				svg.setAttribute('aria-hidden', 'true');
				const path = doc.createElementNS(svg.namespaceURI, 'path');
				path.setAttribute('d', RIBBON_ICON_PATHS[icon] ?? RIBBON_ICON_PATHS.palette);
				if (!svg.childElementCount) {
					svg.append(path);
				}
				const label = doc.createElement('span');
				label.textContent = title;
				trigger.append(svg, label);
			}
			if (!command) {
				const chevron = doc.createElement('span');
				chevron.textContent = '\u2304';
				chevron.setAttribute('aria-hidden', 'true');
				trigger.append(chevron);
			}
			strip.hidden = !inline;
			strip.style.display = inline ? '' : 'none';
			strip.replaceChildren(
				...(inline
					? inlineGalleryItems(descriptor).map((item) =>
							tile(
								item,
								descriptor.sections[0]?.tileWidth ?? 40,
								descriptor.sections[0]?.tileHeight ?? 30,
								disabled,
								t,
							),
						)
					: []),
			);
			popup.setAttribute('aria-label', title);
			popup.replaceChildren(
				...(open ? descriptor.sections : []).map((section) => {
					const container = doc.createElement('section');
					container.className = 'section';
					if (section.titleKey || section.title) {
						const heading = doc.createElement('div');
						heading.className = 'heading';
						heading.textContent = section.titleKey
							? caption(t, section.titleKey, section.title ?? '')
							: (section.title ?? '');
						container.append(heading);
					}
					const grid = doc.createElement('div');
					grid.className = 'grid';
					grid.style.gridTemplateColumns = `repeat(${section.columns}, minmax(0, 1fr))`;
					grid.append(
						...section.items.map((item) =>
							tile(item, section.tileWidth, section.tileHeight, disabled, t),
						),
					);
					container.append(grid);
					return container;
				}),
			);
		},
	};
}
